// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3,oneof" json:"created,omitempty"`
	Updated       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated,proto3,oneof" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMetadata) Reset() {
	*x = SecretMetadata{}
	mi := &file_api_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMetadata) ProtoMessage() {}

func (x *SecretMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMetadata.ProtoReflect.Descriptor instead.
func (*SecretMetadata) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *SecretMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SecretMetadata) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *SecretMetadata) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_api_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{1}
}

type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretMetadata      `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_api_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretsResponse) GetSecrets() []*SecretMetadata {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type AddSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SecretMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSecretRequest) Reset() {
	*x = AddSecretRequest{}
	mi := &file_api_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSecretRequest) ProtoMessage() {}

func (x *AddSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSecretRequest.ProtoReflect.Descriptor instead.
func (*AddSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *AddSecretRequest) GetMeta() *SecretMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *AddSecretRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AddSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SecretMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSecretResponse) Reset() {
	*x = AddSecretResponse{}
	mi := &file_api_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSecretResponse) ProtoMessage() {}

func (x *AddSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSecretResponse.ProtoReflect.Descriptor instead.
func (*AddSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *AddSecretResponse) GetMeta() *SecretMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_api_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *SecretMetadata        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_api_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *GetSecretResponse) GetMeta() *SecretMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetSecretResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_api_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_api_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{8}
}

var File_api_keeper_proto protoreflect.FileDescriptor

const file_api_keeper_proto_rawDesc = "" +
	"\n" +
	"\x10api/keeper.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x0eSecretMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\acreated\x88\x01\x01\x129\n" +
	"\aupdated\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aupdated\x88\x01\x01B\n" +
	"\n" +
	"\b_createdB\n" +
	"\n" +
	"\b_updated\"\x13\n" +
	"\x11GetSecretsRequest\"C\n" +
	"\x12GetSecretsResponse\x12-\n" +
	"\asecrets\x18\x01 \x03(\v2\x13.api.SecretMetadataR\asecrets\"U\n" +
	"\x10AddSecretRequest\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.api.SecretMetadataR\x04meta\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"<\n" +
	"\x11AddSecretResponse\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.api.SecretMetadataR\x04meta\"&\n" +
	"\x10GetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x11GetSecretResponse\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.api.SecretMetadataR\x04meta\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\")\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteSecretResponse2\x84\x02\n" +
	"\x06Keeper\x12=\n" +
	"\n" +
	"GetSecrets\x12\x16.api.GetSecretsRequest\x1a\x17.api.GetSecretsResponse\x12:\n" +
	"\tAddSecret\x12\x15.api.AddSecretRequest\x1a\x16.api.AddSecretResponse\x12:\n" +
	"\tGetSecret\x12\x15.api.GetSecretRequest\x1a\x16.api.GetSecretResponse\x12C\n" +
	"\fDeleteSecret\x12\x18.api.DeleteSecretRequest\x1a\x19.api.DeleteSecretResponseB\vZ\tpkg/protob\x06proto3"

var (
	file_api_keeper_proto_rawDescOnce sync.Once
	file_api_keeper_proto_rawDescData []byte
)

func file_api_keeper_proto_rawDescGZIP() []byte {
	file_api_keeper_proto_rawDescOnce.Do(func() {
		file_api_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_keeper_proto_rawDesc), len(file_api_keeper_proto_rawDesc)))
	})
	return file_api_keeper_proto_rawDescData
}

var file_api_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_keeper_proto_goTypes = []any{
	(*SecretMetadata)(nil),        // 0: api.SecretMetadata
	(*GetSecretsRequest)(nil),     // 1: api.GetSecretsRequest
	(*GetSecretsResponse)(nil),    // 2: api.GetSecretsResponse
	(*AddSecretRequest)(nil),      // 3: api.AddSecretRequest
	(*AddSecretResponse)(nil),     // 4: api.AddSecretResponse
	(*GetSecretRequest)(nil),      // 5: api.GetSecretRequest
	(*GetSecretResponse)(nil),     // 6: api.GetSecretResponse
	(*DeleteSecretRequest)(nil),   // 7: api.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 8: api.DeleteSecretResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_keeper_proto_depIdxs = []int32{
	9,  // 0: api.SecretMetadata.created:type_name -> google.protobuf.Timestamp
	9,  // 1: api.SecretMetadata.updated:type_name -> google.protobuf.Timestamp
	0,  // 2: api.GetSecretsResponse.secrets:type_name -> api.SecretMetadata
	0,  // 3: api.AddSecretRequest.meta:type_name -> api.SecretMetadata
	0,  // 4: api.AddSecretResponse.meta:type_name -> api.SecretMetadata
	0,  // 5: api.GetSecretResponse.meta:type_name -> api.SecretMetadata
	1,  // 6: api.Keeper.GetSecrets:input_type -> api.GetSecretsRequest
	3,  // 7: api.Keeper.AddSecret:input_type -> api.AddSecretRequest
	5,  // 8: api.Keeper.GetSecret:input_type -> api.GetSecretRequest
	7,  // 9: api.Keeper.DeleteSecret:input_type -> api.DeleteSecretRequest
	2,  // 10: api.Keeper.GetSecrets:output_type -> api.GetSecretsResponse
	4,  // 11: api.Keeper.AddSecret:output_type -> api.AddSecretResponse
	6,  // 12: api.Keeper.GetSecret:output_type -> api.GetSecretResponse
	8,  // 13: api.Keeper.DeleteSecret:output_type -> api.DeleteSecretResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_keeper_proto_init() }
func file_api_keeper_proto_init() {
	if File_api_keeper_proto != nil {
		return
	}
	file_api_keeper_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_keeper_proto_rawDesc), len(file_api_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_keeper_proto_goTypes,
		DependencyIndexes: file_api_keeper_proto_depIdxs,
		MessageInfos:      file_api_keeper_proto_msgTypes,
	}.Build()
	File_api_keeper_proto = out.File
	file_api_keeper_proto_goTypes = nil
	file_api_keeper_proto_depIdxs = nil
}
