// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_api_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Secret) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SecretDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDescription) Reset() {
	*x = SecretDescription{}
	mi := &file_api_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDescription) ProtoMessage() {}

func (x *SecretDescription) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDescription.ProtoReflect.Descriptor instead.
func (*SecretDescription) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{1}
}

func (x *SecretDescription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretDescription) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_api_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsRequest.ProtoReflect.Descriptor instead.
func (*GetSecretsRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{2}
}

type GetSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretDescription   `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_api_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretsResponse.ProtoReflect.Descriptor instead.
func (*GetSecretsResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretsResponse) GetSecrets() []*SecretDescription {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type AddSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSecretRequest) Reset() {
	*x = AddSecretRequest{}
	mi := &file_api_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSecretRequest) ProtoMessage() {}

func (x *AddSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSecretRequest.ProtoReflect.Descriptor instead.
func (*AddSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *AddSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSecretRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddSecretRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type AddSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSecretResponse) Reset() {
	*x = AddSecretResponse{}
	mi := &file_api_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSecretResponse) ProtoMessage() {}

func (x *AddSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSecretResponse.ProtoReflect.Descriptor instead.
func (*AddSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{5}
}

func (x *AddSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddSecretResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_api_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *GetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_api_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSecretResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetSecretResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_api_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_api_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_keeper_proto_rawDescGZIP(), []int{9}
}

var File_api_keeper_proto protoreflect.FileDescriptor

const file_api_keeper_proto_rawDesc = "" +
	"\n" +
	"\x10api/keeper.proto\x12\x03api\"J\n" +
	"\x06Secret\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\";\n" +
	"\x11SecretDescription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x13\n" +
	"\x11GetSecretsRequest\"F\n" +
	"\x12GetSecretsResponse\x120\n" +
	"\asecrets\x18\x01 \x03(\v2\x16.api.SecretDescriptionR\asecrets\"T\n" +
	"\x10AddSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\";\n" +
	"\x11AddSecretResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"&\n" +
	"\x10GetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"U\n" +
	"\x11GetSecretResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\")\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteSecretResponse2\x84\x02\n" +
	"\x06Keeper\x12=\n" +
	"\n" +
	"GetSecrets\x12\x16.api.GetSecretsRequest\x1a\x17.api.GetSecretsResponse\x12:\n" +
	"\tAddSecret\x12\x15.api.AddSecretRequest\x1a\x16.api.AddSecretResponse\x12:\n" +
	"\tGetSecret\x12\x15.api.GetSecretRequest\x1a\x16.api.GetSecretResponse\x12C\n" +
	"\fDeleteSecret\x12\x18.api.DeleteSecretRequest\x1a\x19.api.DeleteSecretResponseB\vZ\tpkg/protob\x06proto3"

var (
	file_api_keeper_proto_rawDescOnce sync.Once
	file_api_keeper_proto_rawDescData []byte
)

func file_api_keeper_proto_rawDescGZIP() []byte {
	file_api_keeper_proto_rawDescOnce.Do(func() {
		file_api_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_keeper_proto_rawDesc), len(file_api_keeper_proto_rawDesc)))
	})
	return file_api_keeper_proto_rawDescData
}

var file_api_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_keeper_proto_goTypes = []any{
	(*Secret)(nil),               // 0: api.Secret
	(*SecretDescription)(nil),    // 1: api.SecretDescription
	(*GetSecretsRequest)(nil),    // 2: api.GetSecretsRequest
	(*GetSecretsResponse)(nil),   // 3: api.GetSecretsResponse
	(*AddSecretRequest)(nil),     // 4: api.AddSecretRequest
	(*AddSecretResponse)(nil),    // 5: api.AddSecretResponse
	(*GetSecretRequest)(nil),     // 6: api.GetSecretRequest
	(*GetSecretResponse)(nil),    // 7: api.GetSecretResponse
	(*DeleteSecretRequest)(nil),  // 8: api.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 9: api.DeleteSecretResponse
}
var file_api_keeper_proto_depIdxs = []int32{
	1, // 0: api.GetSecretsResponse.secrets:type_name -> api.SecretDescription
	2, // 1: api.Keeper.GetSecrets:input_type -> api.GetSecretsRequest
	4, // 2: api.Keeper.AddSecret:input_type -> api.AddSecretRequest
	6, // 3: api.Keeper.GetSecret:input_type -> api.GetSecretRequest
	8, // 4: api.Keeper.DeleteSecret:input_type -> api.DeleteSecretRequest
	3, // 5: api.Keeper.GetSecrets:output_type -> api.GetSecretsResponse
	5, // 6: api.Keeper.AddSecret:output_type -> api.AddSecretResponse
	7, // 7: api.Keeper.GetSecret:output_type -> api.GetSecretResponse
	9, // 8: api.Keeper.DeleteSecret:output_type -> api.DeleteSecretResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_keeper_proto_init() }
func file_api_keeper_proto_init() {
	if File_api_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_keeper_proto_rawDesc), len(file_api_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_keeper_proto_goTypes,
		DependencyIndexes: file_api_keeper_proto_depIdxs,
		MessageInfos:      file_api_keeper_proto_msgTypes,
	}.Build()
	File_api_keeper_proto = out.File
	file_api_keeper_proto_goTypes = nil
	file_api_keeper_proto_depIdxs = nil
}
